# Generated by Django 6.1 on 2026-09-26 03:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Camisas', 'Camisas'), ('Vestidos', 'Vestidos'), ('Alfaiataria', 'Alfaiataria'), ('Saias', 'Saias')], default='Camisas', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_antigo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preencha só se o produto estiver em oferta.', max_digits=8, null=True),
        ),
    ]
