# Generated by Django 6.1 on 2026-09-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_produto_options_produto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('imagem', models.ImageField(blank=True, upload_to='colecoes/')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Números menores aparecem primeiro no carrossel.')),
            ],
        ),
    ]
