# Generated by Django 6.1 on 2026-09-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_colecao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colecao',
            options={'ordering': ['ordem'], 'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
    ]
