# Generated by Django 6.1 on 2026-09-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_colecao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False, help_text="Marque para este produto aparecer na seção 'Mais Vendidos'."),
        ),
    ]
