# Generated by Django 6.1 on 2026-10-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_produto_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='colecoes',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='app.colecao', verbose_name='Coleções'),
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app.produto')),
            ],
            options={
                'verbose_name': 'Foto do produto',
                'verbose_name_plural': 'Fotos do produto',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
