# Generated by Django 6.1 on 2026-10-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_produto_colecoes_produtoimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(default=10, help_text='Quando chegar a 0, o produto aparece como indisponível.', verbose_name='Quantidade em estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Camisas', 'Camisas'), ('Calças', 'Calças'), ('Sapatos', 'Sapatos'), ('Bonés', 'Bonés')], max_length=50),
        ),
    ]
